[build]
publish = "build/"
command = "yarn build"

REACT_APP_CONTENTFUL_ACCESS_TOKEN  = process.env.REACT_APP_CONTENTFUL_ACCESS_TOKEN
REACT_APP_CONTENTFUL_SPACE = process.env.REACT_APP_CONTENTFUL_SPACE
